// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Hello(Props) {
  return React.createElement("div", undefined, String("ברוכים הבאים!"));
}

var make = Hello;

var $$default = Hello;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
