// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Hello(Props) {
  return React.createElement("div", undefined, String("\xd7\x91\xd7\xa8\xd7\x95\xd7\x9b\xd7\x99\xd7\x9d \xd7\x94\xd7\x91\xd7\x90\xd7\x99\xd7\x9d!"));
}

var make = Hello;

var $$default = Hello;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
